name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        # options: ['info', 'debug', 'trace']
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
      - name: Build and Deploy
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        with:
          name: GPabis/TSP-Frontend/tsp-frontend
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: VITE_API_URL
          dockerfile: Dockerfile
          tags: "latest,${{ steps.pre-step.outputs.release-version }}"
      - name: Deploy package to vps
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          envs: GITHUB_USERNAME,GITHUB_TOKEN
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull "ghcr.io/gpabis/tsp-frontend/tsp-frontend:latest"
            docker stop tsp-frontend
            docker system prune -f
            docker run --name tsp-frontend -dit -p 3000:80 "ghcr.io/gpabis/tsp-frontend/tsp-frontend:latest"
            
